name: ConvertedIn CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set up Database
        run: php artisan migrate --force

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit

      - name: Run Background Job for Updating Statistics Table
        run: php artisan update:statistics

      - name: Run Queue Worker
        run: php artisan queue:work --stop-when-empty
